---
- name: update sysctl
  command: sysctl -e -p /etc/sysctl.d/riak.conf

- name: source rclocal
  command: /bin/bash /etc/rc.local

- name: restart riak
  service: name=riak state=restarted

- name: wait for http
  wait_for: port={{ riak_http_port }}

- name: wait for kv
  riak: wait_for_service=kv

- name: commit cluster changes
  riak: command=commit

- name: wait for handoffs
  riak: wait_for_handoffs=1200

- name: wait for ring
  riak: wait_for_ring=600
